### ISSUE TITLE
Failing to validate a corpus (large)

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Ngram#13]
In validating a large number of items (4981), items are not added to corpus.

Items are validated, but upon return to manage corpus page- it states that "valid items were accepted" but none of the items have been added, unigrams/bigrams can't be generated. (See screenshots)
![screen shot 2016-03-01 at 1 48 49 pm](https://cloud.githubusercontent.com/assets/5897725/13438285/620d62ce-dfb6-11e5-9757-ab463de7255d.png)
![screen shot 2016-03-01 at 1 49 00 pm](https://cloud.githubusercontent.com/assets/5897725/13438288/6717e3b6-dfb6-11e5-8275-a12a0c868290.png)

**Comment by jimsafley** [comment]
Was using a data type for `ngram_corpus`.`items_corpus` that could not contain a large corpus. Changed from `text` to `longtext`. Fixed.
