### ISSUE TITLE
Is IntlBreakIterator too obscure a dependency?

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-Ngram#16]
We use [IntlBreakIterator](http://php.net/manual/en/class.intlbreakiterator.php) to tokenize text into words. Unfortunately the class may not be widely available even when [intl](http://php.net/manual/en/book.intl.php) is installed. It wasn't added to until [intl 3.0.0a2](https://pecl.php.net/package-changelog.php?package=intl).

Do need some other way to tokenize text into words in case the IntlBreakIterator class doesn't exist? Some potential workarounds:
- [str_word_count](http://php.net/manual/en/function.str-word-count.php) with `format=1`
- [preg_split](http://php.net/manual/en/function.preg-split.php) split on unicode whitespace or word boundaries

**Comment by jimsafley** [comment]
The plugin's `omeka_minimum_version` of 2.4 requires a version of PHP that bundles the intl extension with `IntlBreakIterator`. Closing.

**Comment by NedHenry** [comment]
I'm using Omeka 2.5 with PHP 5.3.3  on Centos 6 and am having this issue. Installing the intl extension using 'yum install php-intl' installs an older version of the extension that does not include the necessary class.
What version of PHP are you referencing that bundles this dependency?

**Comment by zerocrates** [comment]
PHP's documentation on this score is sadly lacking so the answer is surprisingly hard to find.

IntlBreakIterator is available in the bundled-in intl extension on PHP 5.5 or higher. On older versions, you can use the [intl package from PECL](https://pecl.php.net/package/intl), which backports that and other features.

**Comment by NedHenry** [comment]
I had trouble installing the latest intl package from PECL, and ultimately solved the problem by upgrading PHP. Might be worth a note on this project's README that this could be necessary in some cases.
