### ISSUE TITLE
Finalize testing

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-Ngram#18]
@jannellelegg

I've implemented no new features since April and need to know where you stand in testing. How has testing gone on the 911DA data? Other than existing issues, have you discovered any bugs or unexpected behavior? Do you have ideas for improvement? From your perspective, is this plugin ready to be released to the public?

**Comment by jimsafley** [comment]
@mebrett

**Comment by mebrett** [comment]
Jim - is there a specific branch of master that this needs to work?

**Comment by jannellelegg** [comment]
@jimsafley - I'm back at the office now and catching up on requests. I think we need fresh eyes on the interface - I haven't run into additional problems with results. I've checked in with Megan and shared my notes with her so she can start running some tests.
