### ISSUE TITLE
Unable to generate ngrams

### ISSUE THREAD

**Issue by alyssafahringer** [omeka/plugin-Ngram#26]
On my install on the dev server, I have been unable to generate any ngrams. I've tried switching items from private to public and played around with the size of the corpus (from 3,000 to 35) with no luck. I am able to validate the items, but when I click generate unigrams, it hangs there and never generates.

**Comment by jimsafley** [comment]
I made some changes. Pull from master, uninstall then re-install the plugin, and try the process again. It'll probably still not work, but let's see.

**Comment by alyssafahringer** [comment]
Pulled from master, uninstalled and then reinstalled. I've tried with three different corpora to no success - it is still hanging.

**Comment by jimsafley** [comment]
[Activate error logging](https://omeka.org/codex/Retrieving_Error_Messages#Activate_Error_Logging) and check the log. Near the bottom you should see "Ngram generation START", hopefully followed by an error. Paste that here.

**Comment by alyssafahringer** [comment]
I checked the errors log and there was no error message there. I spoke with Jannelle and we went through all the steps that the two of you had tried whenever she would get an error and we were unable to uncover any error messages. I also do not have access to the mysql database. If it's helpful, I can create an account on my install for you if you need to poke around.

**Comment by jimsafley** [comment]
Did you see an "Ngram generation START" message in the log? If not then you probably don't have logging completely enabled. If so, and it's not followed by any other message, then there was probably a fatal error during the process. That could mean you're reaching the memory limit. How many items are in your corpus? About how large is the average text in the text element? There are other things we could check, but if you don't have access to the database there's not much we can do to troubleshoot this.

Yes, I'd like an account. Thanks.

**Comment by alyssafahringer** [comment]
It is a corpus of 1999 items. There isn't a significant amount of text in the text element, which I have configured to title.

**Comment by jimsafley** [comment]
Any progress on creating an account for me on your install?

**Comment by alyssafahringer** [comment]
I just re-sent the activation email. I'm using your GMU email - please let me know if you want me to use a different one.

**Comment by jimsafley** [comment]
I received no activation emails. It could be that the dev server isn't set up to send email. @rsanc77 could you take a look?
