### ISSUE TITLE
Add ability for users to delete corpora

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-Ngram#27]
With lots of people using the tool, it's easy to build up lots of cruft corpora. Can we have a delete link for each of them?

**Comment by jimsafley** [comment]
You can delete a corpus on the corpus show page.

**Comment by sharonmleon** [comment]
We might have a bug then, or a configuration problem. We have no active delete buttons on http://dev.911digitalarchive.org/

**Comment by jimsafley** [comment]
I see it now. This is a consequence of a protection I put into place that prevents data corruption. A user cannot delete a corpus if a ngram generation process is running. In fact, if a process is running a user can't even generate ngrams . If you create a new corpus does it allow you to generate ngrams?

**Comment by sharonmleon** [comment]
Nope. So maybe we have a process build up, and we should just clear them. (The build up might be from me refusing to read the documentation and screwing things up several times.)

My home IP address isn't on the whitelist, so I'm stuck for now.

**Comment by jimsafley** [comment]
I remembered that I accounted for this. Go to plugin configuration, check the "Reset Processes" box, and save the changes. The delete and generate buttons should be active.

**Comment by sharonmleon** [comment]
Thanks, Jim. We'll clear them out.
